export const Projects = [
  {
    id: 1,
    title: "캐릭터 능력치 홈페이지",
    desc: "chackbox와 label을 활용한 이벤트",
    main: "javaScript",
    sub: "none",
    people: "solo",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
  {
    id: 2,
    title: "제품홍보 홈페이지",
    desc: "여러 기업들의 제품 페이지를 찾아보고 적용해본 프로젝트",
    main: "javaScript",
    sub: "none",
    people: "solo",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
  {
    id: 3,
    title: "마켓컬리 디벨롭",
    desc: "마켓컬리를 따라 만들고 유저 서치 후 UI 변경도 해본 디벨롭 페이지",
    main: "javaScript",
    sub: "slickSlider",
    people: "Team",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
  {
    id: 4,
    title: "쓰레드",
    desc: "마켓컬리를 따라 만들고 유저 서치 후 UI 변경도 해본 디벨롭 페이지",
    main: "react",
    sub: "slickSlider",
    people: "Team",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
  {
    id: 5,
    title: "OTT",
    desc: "마켓컬리를 따라 만들고 유저 서치 후 UI 변경도 해본 디벨롭 페이지",
    main: "typeScript",
    sub: "slickSlider",
    people: "Team",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
  {
    id: 6,
    title: "마켓컬리 디벨롭",
    desc: "마켓컬리를 따라 만들고 유저 서치 후 UI 변경도 해본 디벨롭 페이지",
    main: "javaScript",
    sub: "slickSlider",
    people: "Team",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
  {
    id: 7,
    title: "마켓컬리 디벨롭",
    desc: "마켓컬리를 따라 만들고 유저 서치 후 UI 변경도 해본 디벨롭 페이지",
    main: "javaScript",
    sub: "slickSlider",
    people: "Team",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
  {
    id: 8,
    title: "마켓컬리 디벨롭",
    desc: "마켓컬리를 따라 만들고 유저 서치 후 UI 변경도 해본 디벨롭 페이지",
    main: "javaScript",
    sub: "slickSlider",
    people: "Team",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
  {
    id: 9,
    title: "마켓컬리 디벨롭",
    desc: "마켓컬리를 따라 만들고 유저 서치 후 UI 변경도 해본 디벨롭 페이지",
    main: "javaScript",
    sub: "slickSlider",
    people: "Team",
    img: "",
    link: [{ main: "http:\\local3000" }, { figma: "...." }, { issue: "...." }],
  },
];
